### ISSUE TITLE
Some fields aren't displayed correctly

### ISSUE THREAD

**Issue by TheRedTrainer** [NICMx/rdap-text-renderer#2]
If an user retrieves the information from a domain that includes DNSSEC data (such as  ds_data and key_data) some fields aren't displayed correctly. Some fields are displaying strange unicode chars instead of the integers (please see image below) 

![reddog-dnssec](https://user-images.githubusercontent.com/22969079/38390600-62cc47ac-38e7-11e8-8daf-d6b8d6dcb8d7.png)

It is necessary to display all the domain information correctly.

**Comment by dhfelix** [comment]
The expected value of the fields must be an integer.

The function that was used to print those values, receives as a parameter an integer value, but internally the function converts the integer value to a character value, and thats why the renderer prints an incorrect value.

To solve the issue, the integer values are converted to String values, and this way, the renderer prints the correct value.
